### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by GrantPerkins** [technoAl/StockExchangeNeuralNetworkInferenceDevice#1]
This project has a bunch of files/folders that are user-specific or otherwise unintentionally included in the project. This includes .DS_STORE, and .ipynb_checkpoints. Git should ignore these files when commiting. Try using a .gitignore file.

Use a website like [gitignore.io](https://gitignore.io) to generate a .gitignore file. Type in all of the languages and high level tools you are using, and a file will be generated. This will make your projects cleaner.

**Comment by darshankrishnaswamy** [comment]
Has been resolved.
